### ISSUE TITLE
Proofer: nothing appears anymore

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/diffenator2#106]
Using gftools 0.9.36 and diffenator2 0.3.2
For "Old" and "New', nothing appears anymore in diffbrowsers_proofer.html

<img width="1421" alt="Capture d’écran 2023-11-08 à 11 32 08" src="https://github.com/googlefonts/diffenator2/assets/64773544/6eee05eb-955b-40a6-9be6-a9e0343b5111">

**Comment by emmamarichal** [comment]
I tested it on several fonts but here is the file I used for the screenshot: 
[variable.zip](https://github.com/googlefonts/diffenator2/files/13295533/variable.zip)

**Comment by emmamarichal** [comment]
Oh ok, thanks!

**Comment by m4rc1e** [comment]
Yesterday we updated the test strings in the glyphsets repo, https://github.com/googlefonts/glyphsets/pull/146. We can now specify languages for each string so we can test locl features.

**Comment by m4rc1e** [comment]
<img width="1552" alt="Screenshot 2023-11-08 at 10 39 01" src="https://github.com/googlefonts/diffenator2/assets/7525512/6a28d88f-b6f6-47a0-8a76-589b9455325b">

Works well for me.

**Comment by emmamarichal** [comment]
Yes great, I just updated the glyphset and it works! thx!!
