### ISSUE TITLE
diffbrower images (gif) not working so much anymore

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/diffenator2#120]
I can't say at which version it changed but the gif images are having issue:

- From the google/fonts CI we are receiving images only for Firefox
- The glyphset page show the old but is empty for the new
- The text page is cropped (making it hard to see the non-latin text)

So only looking at the html pages at the moment.

Cf [diffbrowsers.zip](https://github.com/googlefonts/diffenator2/files/13561044/diffbrowsers.zip)

**Comment by m4rc1e** [comment]
Thanks for reporting. I'll look into it this week.

**Comment by m4rc1e** [comment]
Fixed in google/fonts
