### ISSUE TITLE
Cannot run Diffenator since there are no fonts before

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/diffenator2#133]
I have this error when I run `gftools qa -f *.ttf -a -gfb` on https://github.com/emmamarichal/Voltaire/tree/main/fonts/ttf
(but I also have it on some other fonts)

```
Cannot run Diffenator since there are no fonts before
Cannot run diffbrowsers since there are no fonts before
```

But, the 'font before' exists and is here in the folder generated by the tool. (I also compared the versions, I have 1.008 and 1.009, so all look good)

<img width="832" alt="Screenshot 2024-04-05 at 14 45 05" src="https://github.com/googlefonts/diffenator2/assets/64773544/a7872812-52c4-4fe3-a421-06e98bcdaa47">

**Comment by emmamarichal** [comment]
I then tried

`diffenator2 diff -fb /Users/marichalemma/Google/forks/Voltaire/fonts/ttf/out/fonts_before/Voltaire-Regular.ttf  -fa /Users/marichalemma/Google/forks/Voltaire/fonts/ttf/Voltaire-Regular.ttf `

and got this: 

```
[2/2] _diffenator "{'fonts_before': ['/Users/marichalemma/G...mma/Google/forks/Voltaire/fonts/ttf/Voltaire-Regular.ttf'}
100%|██████████| 726/726 [00:00<00:00, 3986.01it/s]
100%|██████████| 11/11 [00:00<00:00, 1313.59it/s]
100%|██████████| 594761/594761 [00:31<00:00, 18672.38it/s]
No wordlist for Inherited
```

**Comment by m4rc1e** [comment]
Fixing in https://github.com/googlefonts/gftools/pull/910
