### ISSUE TITLE
[diffbrowsers_glyphs.html] is not showing the changes

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/diffenator2#68]
The glyphs report is useful for checking all the glyphs in an organized table at once and quickly spotting both the changed and unchanged glyphs.

Currently, this report is not working as usual: 
- It is not showing the differences (it seems to be using only the "old" glyphs for both results)
- It is not showing the glyphs in the ordered way it used to but in a random way. At first, it looked like it was using the same table shown in the `diffenator.html` report under the `Modified encoded Glyphs`, but after a second look, they are not the same.

**Previous report preview:**
![Old-report-preview](https://github.com/googlefonts/diffenator2/assets/48698976/d975ced2-eb35-4155-9c12-2f16a7383b43)

**New report preview:**
![New-report-preview](https://github.com/googlefonts/diffenator2/assets/48698976/3c9f37cb-1d3f-4e79-8221-92e4a484d68e)

**Files to replicate**
I'm attaching two zip files that include all the reports + fonts used: 

- Feb 28 - working ok (sadly, I don't recall the Diffenator2 version)
    [Francois-diff-GF-Jacques-60pt-28Feb.zip](https://github.com/googlefonts/diffenator2/files/11900729/Francois-diff-GF-Jacques-60pt-28Feb.zip)
- Jun 27 - not working (Diffenator2 v0.2.5)
    [Francois-diff-GF-Jacques-60pt-Jun27.zip](https://github.com/googlefonts/diffenator2/files/11900730/Francois-diff-GF-Jacques-60pt-Jun27.zip)

I've tried it with different fonts but this case is a good example since the expected differences are evident.

**Comment by m4rc1e** [comment]
Thanks for the zips! I'l take a look.

**Comment by m4rc1e** [comment]
`diffbrowsers_glyphs.html` is now ordered by unicode.

<img width="1440" alt="Screenshot 2023-07-04 at 17 02 40" src="https://github.com/googlefonts/diffenator2/assets/7525512/8a24d571-de06-4930-aa41-a458bb04b100">

It's available on the main branch. I'll cut a release in the next day or two.

**Comment by vv-monsalve** [comment]
Brilliant! Thank you.
