### ISSUE TITLE
`--user-wordlist` option usage question

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/diffenator2#69]
When using the `--user-wordlist` option in a diffing run with a Vietnamese text, the resulting folder doesn't include the desired sample.

Should the .txt file have a specific format? I've tried two: 

- Standard paragraph text, including periods and commas.
   .txt file used + produced folder: [qaPlaypenS-vf-09-diff-nf-viet2.zip](https://github.com/googlefonts/diffenator2/files/11901149/qaPlaypenS-vf-09-diff-nf-viet2.zip)

- A list of words without punctuation of any kind, following the files seen in [diffenator2/data/wordlists](https://github.com/googlefonts/diffenator2/tree/main/src/diffenator2/data/wordlists) 
    .txt file used + produced folder: [qaPlaypenS-vf-09-diff-nf-viet1.zip](https://github.com/googlefonts/diffenator2/files/11901155/qaPlaypenS-vf-09-diff-nf-viet1.zip)

**Comment by m4rc1e** [comment]
The second list is perfect. We delimit words by newlines.

**Comment by vv-monsalve** [comment]
Ok, thanks for confirming the formatting. Now the next question would be, what is the expected result? 

- Would the .txt file replace the displayed text in `diffbrowsers_text.html`?
- A new `diffbrowsers_vietnamese.html` or `diffbrowsers_wordlist.html` file created showing the used sample?

The produced folder is not including the provided list in any of the resulting .HTML files

**Comment by m4rc1e** [comment]
Sorry, didn't see follow ups.

> Would the .txt file replace the displayed text in diffbrowsers_text.html?

Nope. diffbrowsers_text just produces sample text from the Universal Declaration of Human Rights. It doesn't look at the custom wordlist. Perhaps we should do this?

> A new diffbrowsers_vietnamese.html or diffbrowsers_wordlist.html file created showing the used sample?

I'll think about that one. I could add the Vietnamese characters to the proofing page?

**Comment by vv-monsalve** [comment]
> Nope. diffbrowsers_text just produces sample text from the Universal Declaration of Human Rights. It doesn't look at the custom wordlist. Perhaps we should do this?

I understand the `diffbrowsers_text` uses the sample from the Universal Declaration. The question was oriented toward understanding the expected result when using the wordlist option cause I did not see the provided string anywhere, so guessing one possibility was the output could be displayed in that "text.html". However, it's clear now what the usage is, from your answer in the other issue Stephen opened about this: "The output is in diffenator2-report.html under the heading "Misshapen user strings".

> I'll think about that one. I could add the Vietnamese characters to the proofing page?

Thanks. I think on the proofing page, we are testing core _musts_ for fonts, and Vietnamese or other specifics like the OT Stephen mentions in the other issue, are advanced features per each font case.

It would be amazing to have the option to see the provided sample by the user's "wordlist.txt" on a separate output page, even if there is no difference reported. Similar to what `gen-html` allowed when using custom templates either under the `diff` or `proof` options.

**Comment by m4rc1e** [comment]
Sorry, I didn't mention that the `--user-wordlist` arg output is in the `diffenator2-report.html` file, under the heading "Misshapen user strings". If it's empty, it means it couldn't find any differences.

**Comment by vv-monsalve** [comment]
> It would be amazing to have the option to see the provided sample by the user's "wordlist.txt" on a separate output page, even if there is no difference reported. Similar to what `gen-html` allowed when using custom templates either under the `diff` or `proof` options.

Could this be feasible? In the diff option, the `diffbrowsers_text.html` is produced even if there are no differences between the compared fonts. This is really useful to confirm this visually. 

Alternatively, if not desired when diffing, could this be added to the `proof` functionality?

**Comment by m4rc1e** [comment]
Let's add another page `user-strings.html`. My only concern is that we already have some projects which have user wordlists which have over 100k words 😿 so the reports are going to be huge. I'll think of something.

Thanks for your suggestions.

**Comment by vv-monsalve** [comment]
> Let's add another page `user-strings.html`.

Awesome! Perhaps a limit for the `.txt` could be suggested/required?

Thank you for the work on the tool.

**Comment by vv-monsalve** [comment]
A separate `diffbrowsers_user_strings.html` is produced now when using the `--user-wordlist` option even at `proof` usage in the `0.2.13` version. Thank you!

I now have another suggestion for it, but I'll create a new issue for it, so I'm closing this issue here.
