### ISSUE TITLE
`KeyError: 'wght'` received for fonts without `wght` axis

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/diffenator2#79]
The `KeyError: 'wght'` is reported when trying to create proofing docs for fonts that don't have a `wght` axis.

Version: `2.7`

Command used: `diffenator2 proof path/to/font -pt 24 --imgs -o path/to/output`

Complete traceback + Resources to replicate: attached .zip file

[no-wght-fonts.zip](https://github.com/googlefonts/diffenator2/files/12152719/no-wght-fonts.zip)

**Comment by m4rc1e** [comment]
Thanks for the testcase!
